const p1={nome:'Afeganistão',cap:'Cabul',cont:'Ásia'}
const p2={nome:'África do sul',cap:'Pretória',cont:'África'}
const p3={nome:'Albânia',cap:'Tirana',cont:'Europa'}
const p4={nome:'Alemanha',cap:'Berlim',cont:'Europa'}
const p5={nome:'Andorra',cap:'Andorra-a-Velha',cont:'Europa'}
const p6={nome:'Angola',cap:'África'};
const p7={nome:'Antiga e Barbuda',cap:'São João',cont:'América'}
const p8={nome:'Arábia Saudita',cap:'Riade',cont:'Ásia'}
const p9={nome:'Argélica',cap:'Argel',cont:'África'}
const p10={nome:'Argentina',cap:'Buenos Aires',cont:'América'}
const p11={nome:'Armênia',cap:'Erevã',cont:'Ásia'}
const p12={nome:'Austrália',cap:'Camberra',cont:'Oceania'};
const p13={nome:'Áustria',cap:'Viena',cont:'Europa'}
const p14={nome:'Azerbaijão',cap:'Bacu',cont:'Ásia'}
const p15={nome:'Bahamas',cap:'Nassau',cont:'América'}
const p16={nome:'Bangladexe',cap:'Daca',cont:'Ásia'}
const p17={nome:'Barbados',cap:'Bridgetown',cont:'América'}
const p18={nome:'Barém',cap:'Manama',cont:'Ásia'}
const p19={nome:'Bélgica',cap:'Bruxelas',cont:'Europa'}
const p20={nome:'Belize',cap:'Belmopã',cont:'América'}
const p21={nome:'Benim',cap:'Porto Novo',cont:'África'}
const p22={nome:'Bielorrússia',cap:'Minsque',cont:'Europa'}
const p23={nome:'Bolívia',cap:'Sucre',cont:'América'}
const p24={nome:'Bósnia e Herzegovina',cap:'Saraievo',cont:'Europa'}
const p25={nome:'Botsuana',cap:'Gaborone',cont:'África'}
const p26={nome:'BRASIL',cap:'Brasília',cont:'América'}
const p27={nome:'Brunei',cap:'Bandar Seri Begauã',cont:'Ásia'}
const p28={nome:'Bulgária',cap:'Sófia',cont:'Europa'}
const p29={nome:'Burquina Faso',cap:'Uagadugu',cont:'África'}
const p30={nome:'Burúndi',cap:'Bujumbura',cont:'África'}
const p31={nome:'Butão',cap:'Timbu',cont:'Ásia'}
const p32={nome:'Cabo Verde',cap:'Praia',cont:'África'}
const p33={nome:'Camarões',cap:'Laundé',cont:'África'}
const p34={nome:'Camboja',cap:'Pnom Pene',cont:'Ásia'}
const p35={nome:'Canadá',cap:'Otava',cont:'América'}
const p36={nome:'Catar',caap:'Doa',cont:'Ásia'}
const p37={nome:'Cazaquistão',cap:'Astana',cont:'Ásia'}
const p38={nome:'Chade',cap:'Jamena',cont:'África'}
const p39={nome:'Chile',cap:'Santiago',cont:'América'}
const p40={nome:'China',cap:'Pequim',cont:'Ásia'}
const p41={nome:'Chipre',cap:'Nicósia',cont:'Europa'}
const p42={nome:'Colômbia',cap:'Bogotá',cont:'Europa'}
const p43={nome:'Comores',cap:'Moroni',cont:'África'}
const p44={nome:'Congo-Brazzaville',cap:'Brazavile',cont:'África'}
const p45={nome:'Coreia do Norte',cap:'Pionguiangue',cont:'Ásia'}
const p46={nome:'Coreia do Sul',cap:'Seul',cont:'Ásia'}
const p47={nome:'Cosovo',cap:'Pristina',cont:'Europa'}
const p48={nome:'Costa do Marfim',cap:'Lamassucro',cont:'África'}
const p49={nome:'Costa Rica',cap:'São José',cont:'América'}
const p50={nome:'Croácia',cap:'Zagrebe',cont:'Europa'}
const p51={nome:'Cuaite',cap:'Cidade do Cuaite',cont:'Ásia'}
const p52={nome:'Cuba',cap:'Havana',cont:'América'}
const p53={nome:'Dinamarca',cap:'Copenhaga',cont:'Europa'}
const p54={nome:'Dominica',cap:'Roseau',cont:'América'}
const p55={nome:'Egito',cap:'Cairo',cont:'África'}
const p56={nome:'Emirados Árabes Unidos',cap:'Abu Dabi',cont:'Ásia'}
const p57={nome:'Equador',cap:'Quito',cont:'América'}
const p58={nome:'Eritreia',cap:'Asmara',cont:'África'}
const p59={nome:'Eslováquia',cap:'Bratislava',cont:'Europa'}
const p60={nome:'ESlovénia',cap:'Liubliana',cont:'Europa'}
const p61={nome:'Espanha',cap:'Madrid',cont:'Europa'}
const p62={nome:'Essuatíni',cap:'Lobamba',cont:'África'}
const p63={nome:'Estado da Palestina',cap:'Jerusalém Oriental',cont:'Ásia'}
const p64={nome:'Estados Unidos',cap:'Washington',cont:'América'}
const p65={nome:'Estónia',cap:'Talim',cont:'Europa'}
const p66={nome:'Etiópia',cap:'Adis Abeba',cont:'África'}
const p67={nome:'Fiji',cap:'Suva',cont:'Oceania'}
const p68={nome:'Filipinas',cap:'Manila',cont:'Ásia'}
const p69={nome:'Finlândia',cap:'Helsínquia',cont:'Europa'}
const p70={nome:'França',cap:'Paris',cont:'Europa'}
const p71={nome:'Gabão',cap:'Libreville',cont:'África'}
const p72={nome:'Gâmbia',cap:'Banjul',cont:'África'}
const p73={nome:'Gana',cap:'Acra',cont:'África'}
const p74={nome:'Geórgia',cap:'Tebilíssi',cont:'Ásia'}
const p75={nome:'Granada',cap:'São Jorge',cont:'América'}
const p76={nome:'Grécia',cap:'Atenas',cont:'Europa'}
const p77={nome:'Guatemala',cap:'Cidade da Guatemala',cont:'América'}
const p78={nome:'Guiana',cap:'Georgetown',cont:'América'}
const p79={nome:'Guiné',cap:'Conacri',cont:'África'}
const p80={nome:'Guiné Equatorial',cap:'Malabo',cont:'África'}
const p81={nome:'Guiné-Bissau',cap:'Bisssau',cont:'África'}
const p82={nome:'Haiti',cap:'Porto Príncipe',cont:'América'}
const p83={nome:'Honduras',cap:'Tegucigalpa',cont:'América'}
const p84={nome:'Hungria',cap:'Budapeste',cont:'Europa'}
const p85={nome:'Lémen',cap:'Saná',cont:'Ásia'}
const p86={nome:'Ilhas Marechal',cap:'Marujo',cont:'Oceania'}
const p87={nome:'Índia',cap:'Nova Déli',cont:'Ásia'}
const p88={nome:'Indonésia',cap:'Jacarta',cont:'Ásia'}
const p89={nome:'Irão',cap:'Teerão',cont:'Ásia'}
const p90={nome:'Iraque',cap:'Bagdade',cont:'Ásia'}
const p91={nome:'Irlanda',cap:'Dublim',cont:'Europa'}
const p92={nome:'Islândia',cap:'Reiquiavique',cont:'Europa'}
const p93={nome:'Israel',cap:'Jerusálem',cont:'Ásia'}
const p94={nome:'Itália',cap:'Roma',cont:'Europa'}
const p95={nome:'Jamaica',cap:'Kingston',cont:'América'}
const p96={nome:'Japão',cap:'Tóquio',cont:'Ásia'}
const p97={nome:'Jibuti',cap:'Jibuti',cont:'África'}
const p98={nome:'Jordânia',cap:'Amã',cap:'Ásia'}
const p99={nome:'Laus',cap:'Vienciana',cont:'Ásia'}
const p100={nome:'Lesoto',cap:'Maaseru',cont:'África'}
const p101={nome:'Letónia',cap:'Riga',cont:'Europa'}
const p102={nome:'Líbano',cap:'Beirute',cont:'Ásia'}
const p103={nome:'Libéria',cap:'Monróvia',cont:'África'}
const p104={nome:'Líbia',cap:'Trípoli',cont:'África'}
const p105={nome:'Listenstaine',cap:'Vaduz',cont:'Europa'}
const p106={nome:'Lituânia',cap:'Vílnius',cont:'Europa'}
const p107={nome:'Luxemburgo',cap:'Luxemburgo',cont:'Europa'}
const p108={nome:'Macedónia do Norte',cap:'Escópia',cont:'Europa'}
const p109={nome:'Madagascar',cap:'Antananarivo',cont:'África'}
const p110={nome:'Malásia',cap:'Cuala Lumpur',cont:'Ásia'}
const p111={nome:'Maláui',cap:'Lilôngue',cont:'África'}
const p112={nome:'Maldivas',cap:'Malé',cont:'Ásia'}
const p113={nome:'Mali',cap:'Bamaco',cont:'África'}
const p114={nome:'Malta',cap:'Valeta',cont:'Europa'}
const p115={nome:'Marrocos',cap:'Rebate',cont:'África'}
const p116={nome:'Maurícia',cap:'Porto Luís',cont:'África'}
const p117={nome:'Mauritânia',cap:'Nuaquechote',cont:'África'}
const p118={nome:'México',cap:'Cidade do México',cont:'América'}
const p119={nome:'Mianmar',cap:'Nepiedó',cont:'Ásia'}
const p120={nome:'Micronésia',cap:'Paliquir',cont:'Oceania'}
const p121={nome:'Moçambique',cap:'Maputo',cont:'África'}
const p122={nome:'Moldávia',cap:'Quixinau',cont:'Europa'}
const p123={nome:'Mónaco',cap:'Mónaco',cont:'Europa'}
const p124={nome:'Mongólia',cap:'Ulã Bator',cont:'Ásia'}
const p125={nome:'Montenegro',cap:'Podgorista',cont:'Europa'}
const p126={nome:'Namímbia',cap:'Vinduque',cont:'África'}
const p127={nome:'Nauru',cap:'Larém',cont:'Oceania'}
const p128={nome:'Nepal',cap:'Catmandu',cont:'Ásia'}
const p129={nome:'Nicarágua',cap:'Manágua',cont:'América'}
const p130={nome:'Níger',cap:'Niamei',cont:'África'}
const p131={nome:'Nígeria',cap:'Abuja',cont:'África'}
const p132={nome:'Noruega',cap:'Oslo',cont:'Europa'}
const p133={nome:'Nova Zelândia',cap:'Wellignton',cont:'Oceania'}
const p134={nome:'Omã',cap:'Mascate',cont:'Ásia'}
const p135={nome:'Países Baixos',cap:'Amesterdão',cont:'Europa'}
const p136={nome:'Palau',cap:'Ngerulmund',cont:'Oceania'}
const p137={nome:'Panamá',cap:'Cidade do Panamá',cont:'América'}
const p138={nome:'Papua Nova Guiné',cap:'Porto Moresby',cont:'Oceania'}
const p139={nome:'Paquistão',cap:'Islamabade',cont:'Ásia'}
const p140={nome:'Paraguai',cap:'Assunção',cont:'América'}
const p141={nome:'Peru',cap:'Lima',cap:'América'}
const p142={nome:'Polônia',cap:'Varsóvia',cont:'Europa'}
const p143={nome:'Portugal',cap:'Lisboa',cont:'Europa'}
const p144={nome:'Quênia',cap:'Nairóbi',cont:'África'}
const p145={nome:'Quirguinistão',cap:'Bisqueque',cont:'Ásia'}
const p146={nome:'Quiribáti',cap:'Taraua do Sul',cont:'Oceania'}
const p147={nome:'Reino Unido',cap:'Londres',cont:'Europa'}
const p148={nome:'República Centro-Africana',cap:'Bangui',cont:'África'}
const p149={nome:'República Checa',cap:'Praga',cont:'Europa'}
const p150={nome:'República Demorática do Congo',cap:'Quinxassa',cont:'África'}
const p151={nome:'República Dominicana',cap:'São Domingos',cont:'América'}
const p152={nome:'Romênia',cap:'Bucareste',cont:'Europa'}
const p153={nome:'Ruanda',cap:'Quigali',cont:'África'}
const p154={nome:'Rússia',cap:'Moscovo',cont:'Europa'}
const p155={nome:'Salomão',cap:'Hoinara',cont:'Oceania'}
const p156={nome:'Salvador',cap:'São Salvador',cont:'América'}
const p157={nome:'Samoa',cap:'Apia',cont:'Oceania'}
const p158={nome:'Santa Lúcia',cap:'Castries',cont:'América'}
const p159={nome:'São cristovão e neves',cap:'Bassetere',cont:'América'}
const p160={nome:'São Marinho',cap:'São Marinho',cont:'Europa'}
const p161={nome:'São Tomé e Príncipe',cap:'São Tomé',cont:'África'}
const p162={nome:'São Vicente e Granadinhas',cap:'Kingstown',cont:'América'}
const p163={nome:'Seicheles',cap:'Vitória',cont:'África'}
const p164={nome:'Senegal',cap:'Dacar',cont:'África'}
const p165={nome:'Serra Leoa',cap:'Freetown',cont:'África'}
const p166={nome:'Sérvia',cap:'Belgrado',cont:'Europa'}
const p167={nome:'Singapura',cap:'Singapura',cont:'Ásia'}
const p168={nome:'Síria',cap:'Damasco',cont:'Ásia'}
const p169={nome:'Somália',cap:'Mogadíscio',cont:'África'}
const p170={nome:'Sri Lanca',cap:'Sri Jaiavardenapura-Cotta',cont:'Ásia'}
const p171={nome:'Sudão',cap:'Cartum',cont:'África'}
const p172={nome:'Sudão do Sul',cap:'Juba',cont:'África'}
const p173={nome:'Suécia',cap:'Estocolmo',cont:'Europa'}
const p174={nome:'Suíça',cap:'Berna',cont:'Europa'}
const p175={nome:'Suriname',cap:'Paramaribo',cont:'América'}
const p176={nome:'Tailândia',cap:'Banguecoque',cont:'Ásia'}
const p177={nome:'Taiuã',cap:'Taipé',cont:'Ásia'}
const p178={nome:'Tajiquistão',cap:'Duchambé',cont:'Ásia'}
const p179={nome:'Tanzânia',cap:'Dodoma',cont:'África'}
const p180={nome:'Timor-Leste',cap:'Díli',cont:'Oceania'}
const p181={nome:'Togo',cap:'Lomé',cont:'África'}
const p182={nome:'Tonga',cap:'Nucualofa',cont:'Oceania'}
const p183={nome:'Trindade e Tobago',cap:'Porto da Espanha',cont:'América'}
const p184={nome:'Tunísia',cap:'Tunes',cont:'África'}
const p185={nome:'Turcomenistão',cap:'Asgabate',cont:'Ásia'}
const p186={nome:'Turquia',cap:'Ancara',cont:'Ásia'}
const p187={nome:'Tuvalu',cap:'Funafuti',cont:'Oceania'}
const p188={nome:'Ucrânia',cap:'Quieve',cont:'Europa'}
const p189={nome:'Uganda',cap:'Campala',cont:'África'}
const p190={nome:'Uruguai',cap:'Montevideu',cont:'América'}
const p191={nome:'Usbequistão',cap:'Tasquente',cont:'Ásia'}
const p192={nome:'Vanuatu',cap:'Porto Vila',cont:'Oceania'}
const p193={nome:'Vaticano',cap:'Vaticano',cont:'Europa'}
const p194={nome:'Venezuela',cap:'Caracas',cont:'América'}
const p195={nome:'Vietnã',cap:'Hanói',cont:'Ásia'}
const p196={nome:'Zâmbia',cap:'Lusaca',cont:'África'}
const p197={nome:'Zimbábue',cap:'Harare',cont:'África'}
re=[p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,
    p21,p22,p23,p24,p25,p26,p27,p28,p29,p30,p31,p32,p33,p34,p35,p36,p37,p38,
    p39,p40,p41,p42,p43,p44,p45,p46,p47,p48,p49,p50,p51,p52,p53,p54,p55,p56,
    p57,p58,p59,p60,p61,p62,p63,p64,p65,p66,p67,p68,p69,p70,p71,p72,p73,p74,
    p75,p76,p77,p78,p79,p80,p81,p82,p83,p84,p85,p86,p87,p88,p89,p90,p91,p92,
    p93,p94,p95,p96,p97,p98,p99,p100,p101,p102,p103,p104,p105,p106,p107,p108,
    p109,p110,p111,p112,p113,p114,p115,p116,p117,p118,p119,p120,p121,p122,p123,
    p124,p125,p126,p127,p128,p129,p130,p131,p132,p133,p134,p135,p136,p137,p138,
    p139,p140,p141,p142,p143,p144,p145,p146,p147,p148,p149,p150,p151,p152,p153,
    p154,p155,p156,p157,p158,p159,p160,p161,p162,p163,p164,p165,p166,p167,p168,
    p169,p170,p171,p172,p173,p174,p175,p176,p177,p178,p179,p180,p181,p182,p183,
    p184,p185,p186,p187,p188,p189,p190,p191,p192,p193,p194,p195,p196,p197
    ]
r=Math.floor(Math.random()*197)
document.getElementById('country').innerHTML=re[r].nome
document.getElementById('cap').innerHTML=re[r].cap
document.getElementById('conti').innerHTML=re[r].cont
function passa(){
    r=Math.floor(Math.random()*197)
    document.getElementById('country').innerHTML=re[r].nome
    document.getElementById('cap').innerHTML=re[r].cap
    document.getElementById('conti').innerHTML=re[r].cont
}
setInterval(passa,2000)